server:
  port: 6262
spring:
  application:
    name: EurekaGatewayMichelangelo
  cloud:
    gateway:
      mvc:
        routes:
        - id: UserMicroservice
          uri: lb://UserMicroservice
          predicates:
            - Path=/user/**
        - id: MediaMicroservice
          uri: lb://MediaMicroservice
          predicates:
            - Path=/media/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server:8761/eureka/


