server:
  port: 6262
spring:
  application:
    name: EurekaGatewayMichelangelo
  cloud:
    gateway:
      mvc:
        routes:
        - id: artistmicroservice
          uri: lb://artistmicroservice
          predicates:
            - Path=/api/v5/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


